config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  get 'landing/index'
  devise_for :users
  root to: 'landing#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :profile
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    profiles_path
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profile = current_user.profile
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id
    respond_to do |format|
      if @profile.save
        format.html { redirect_to profiles_path, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:firstname, :lastname, :sex, :birthdate, :married, :address, :address2, :city, :state, :zip, :phone, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/landing/index.html.erb
<div class="parallax">
  <div class="text-center">
    &nbsp; <p />
    &nbsp; <p />
    &nbsp; <p />
    &nbsp; <p />
    <h1>
      <b>ROYAL FAMILY KIDS</b>
      <light>BRENTWOOD</light>
    </h1>

    <h2 >
      Join us in making moments matter for foster children
    </h2>
    <p />
    &nbsp;
    <hr class="my-4">
    <p />
    &nbsp;

    <%= link_to("Log In", user_session_path, :class=>"btn btn-lg btn-info") %>
    <p />
    <p />
    <%= link_to("create an account", new_user_registration_path, :class=>"btn btn-outline-light") %>

    <p />
    &nbsp;
    <p />
    &nbsp;
    <p />
    &nbsp;
    <p />
    &nbsp;
    <p />
    &nbsp;
    <p />
  </div>
</div>
&nbsp;
<p />
&nbsp;
<p />
&nbsp;
<p />
&nbsp;
<p />
<div class="container" >
  <div class="row">
    <div class="col-md-5">
      <%= image_tag('omar-lopez-rGooKYcscyc-unsplash.jpg', :width=>'100%') %>
    </div>
    <div class="col-md-6" id="white">
      <div style="padding-left:20px">
      &nbsp;
      <p />
      <h4>Volunteer</h4>
      <p>For every counselor willing to spend the entire week at camp, another camper is able to attend.
        Training is mandatory. Counselors arrive at camp the day before the campers to prepare the cabins
        and welcome the campers as they arrive. Each counselor is responsible for two campers in order to
        provide the very best care for our campers. One assistant counselor works with every two regular
        counselors. </p>
      &nbsp;
      <h4>We Need</h4>
      <ul>
        <li>Camp Counselors</li>
        <li>Camp Staff</li>
        <li>Registration Helpers</li>
        <li>Birthday Party Buddies</li>
        <li>Cooks and Servers</li>
      </ul>
        &nbsp;
        <p />
      <div class="text-center">
        <%= link_to("Log In", user_session_path, :class=>"btn btn-info") %>
      <p />
      or
      <br />
      <a href="/users/sign_up">Create an account</a>
      &nbsp;
      <p />
      </div>
      </div>
    </div>
  </div>

</div>
<br />
<br />
<br />
<br />
<br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rfk</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'hello_vue' %>
    <%= stylesheet_pack_tag 'hello_vue' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <br />
          <%= image_tag('RFK-Logo-wht-1024x595.png', :width=>'200px') %>
          <% if user_signed_in? %>
            <%= link_to("Sign Out", destroy_user_session_path, method: :delete	) %>
          <% end %>
        </div>
      </div>
    </div>
    &nbsp; <br />

    <%= yield %>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-row">
    <div class="col-md-4">
      <div class="field">
        <%= form.label :firstname %>
        <%= form.text_field :firstname, :class=>"form-control" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="field">
        <%= form.label :lastname %>
        <%= form.text_field :lastname, :class=>"form-control" %>
      </div>
    </div>
    <div class="col-md-1">
      <div class="field">
        <%= form.label :sex %>
        <%= form.select :sex, options_for_select([["Select One", ""], "Male", "Female"]), :class=>"form-control" %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= form.label :birthdate %>
        <%= form.date_select :birthdate, :start_year=>2004,:end_year=>1900, :order => [:day, :month, :year], :class=>"form-control" %>
      </div>
    </div>
  </div>
  <br />
  <div class="form-row">
    <div class="col-md-2">
      <div class="field">
        <%= form.label :married %><br />
        Yes <%= form.radio_button :married, true, :class=>"" %>
        No <%= form.radio_button :married, false, :class=>"" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="field">
        <%= form.label :address %>
        <%= form.text_field :address, :class=>"form-control" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="field">
        <%= form.label :address2 %>
        <%= form.text_field :address2, :class=>"form-control" %>
      </div>
    </div>
    <div class="col-md-2">
      <div class="field">
        <%= form.label :city %>
        <%= form.text_field :city, :class=>"form-control" %>
      </div>
    </div>
  </div>
  <br />
  <div class="form-row">
    <div class="col-md-2">
      <div class="field">
        <%= form.label :state %>
        <%= form.text_field :state, :class=>"form-control" %>
      </div>
    </div>
    <div class="col-md-2">
      <div class="field">
        <%= form.label :zip %>
        <%= form.text_field :zip, :class=>"form-control" %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= form.label :phone %>
        <%= form.text_field :phone, :class=>"form-control" %>
      </div>
    </div>
  </div>
<div class="row">
  <div class="col-md-6">
    &nbsp;
  </div>
  <div class="col-md-4">
    <div class="actions">
      <br />
      <br />
      <%= form.submit( :class=>'btn btn-info btn-lg btn-block') %>
    </div>
  </div>
</div>

<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<div class="container" id="white">
  <div class="row">
    <div class="col-md-12 text-center">

      <% if @profile == nil %>
        &nbsp; <p />
        <h2>Click the link to get started</h2>
        &nbsp; <p />
        <%= link_to('Start Your Application', new_profile_path, :class=>"btn btn-lg btn-info") %>
      <%else %>


        <p id="notice"><%= notice %></p>

        <h1>Profile</h1>

        <table>
          <thead>
          <tr>
            <th>Firstname</th>
            <th>Lastname</th>
            <th>Sex</th>
            <th>Birthdate</th>
            <th>Married</th>
            <th>Address</th>
            <th>Address2</th>
            <th>City</th>
            <th>State</th>
            <th>Zip</th>
            <th>Phone</th>
            <th>Email</th>
            <th colspan="3"></th>
          </tr>
          </thead>

          <tbody>
          
            <tr>
              <td><%= @profile.firstname %></td>
              <td><%= @profile.lastname %></td>
              <td><%= @profile.sex %></td>
              <td><%= @profile.birthdate %></td>
              <td><%= @profile.married %></td>
              <td><%= @profile.address %></td>
              <td><%= @profile.address2 %></td>
              <td><%= @profile.city %></td>
              <td><%= @profile.state %></td>
              <td><%= @profile.zip %></td>
              <td><%= @profile.phone %></td>
              <td><%= @profile.user.email %></td>
              <td><%= link_to 'Show', @profile %></td>

            </tr>
          
          </tbody>
        </table>

        <br>


        <div id="hello"></div>
      <%end %>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="container" id="white">
  <div class="row">
    <div class="col-md-12 text-center">
      <h1>New Profile</h1>

      <%= render 'form', profile: @profile %>

      <%= link_to 'Back', profiles_path %>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @profile.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @profile.lastname %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @profile.sex %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @profile.birthdate %>
</p>

<p>
  <strong>Married:</strong>
  <%= @profile.married %>
</p>

<p>
  <strong>Address:</strong>
  <%= @profile.address %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @profile.address2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @profile.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @profile.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @profile.zip %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @profile.phone %>
</p>

<p>
  <strong>User:</strong>
  <%= @profile.user_id %>
</p>
<%= link_to 'Destroy', @profile, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>